name = "Mics Mc"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3194c93522bd8d75be0f97a8a72c61e26d233e84a53b97d7682924b4988879"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
