name = "DeathLog"
filename = "deathlog-0.2.6+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3603/579/deathlog-0.2.6+1.18.jar"
hash-format = "murmur2"
hash = "4217565947"

[update]
[update.curseforge]
file-id = 3603579
project-id = 496150
