name = "Default Options (Fabric Edition)"
filename = "defaultoptions-fabric-1.18.1-14.1.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3630/248/defaultoptions-fabric-1.18.1-14.1.0.jar"
hash-format = "murmur2"
hash = "247889447"

[update]
[update.curseforge]
file-id = 3630248
project-id = 547694
