name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3639/38/InventoryProfilesNext-fabric-1.18-1.3.1.jar"
hash-format = "murmur2"
hash = "348541025"

[update]
[update.curseforge]
file-id = 3639038
project-id = 495267
