name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.18.1-1.4.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3622/245/reeses_sodium_options-mc1.18.1-1.4.0.jar"
hash-format = "murmur2"
hash = "3348784607"

[update]
[update.curseforge]
file-id = 3622245
project-id = 511319
