name = "RPMTW Update Mod"
filename = "RPMTW-Update-Mod-Fabric-1.18.1-1.3.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3579/763/RPMTW-Update-Mod-Fabric-1.18.1-1.3.0.jar"
hash-format = "murmur2"
hash = "3290640199"

[update]
[update.curseforge]
file-id = 3579763
project-id = 461500
