name = "RPMTW Update Mod"
filename = "RPMTW-Update-Mod-Fabric-1.18.1-1.3.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ZukQzaRP/versions/1.3.0+118-fabric/RPMTW-Update-Mod-Fabric-1.18.1-1.3.0.jar"
hash-format = "sha512"
hash = "450a247cdd1c24f8cf0bb4554d6365f2791633647ce2e399fc60b0e3a31c5d3e6946af598c0bcda512ee73f1dccccdb026c3fcb4ce78b92b32d2bd26dd1256ff"

[update]
[update.modrinth]
mod-id = "ZukQzaRP"
version = "otnNULko"
