name = "TieFix"
filename = "TieFix-1.9.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3625/238/TieFix-1.9.0.jar"
hash-format = "murmur2"
hash = "2913723209"

[update]
[update.curseforge]
file-id = 3625238
project-id = 560957
