name = "Xaero's Minimap (Fair-play Edition)"
filename = "Xaeros_Minimap_FP22.1.2_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/619/Xaeros_Minimap_FP22.1.2_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "4046795048"

[update]
[update.curseforge]
file-id = 3638619
project-id = 263466
